theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Redux Data Structures
description: Creator functions for common reducers
url: https://redux-data-structures.js.org
google_analytics: UA-103644986-1